apiVersion: apps/v1
kind: Deployment
metadata:
  name: dartscoreboard
spec:
  replicas: 1
  selector:
    matchlabels:
      app: dartscoreboard
    template:
      metadata:
        labels:
          app: dartscoreboard
          version: IMAGE_LABEL
      spec:
        containers:
        - name: dartscoreboard
          image: ACR_URL/dartscoreboard:IMAGE_LABEL
          ports:
          -containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dartscoreboard
spec:
  type: NodePort
  selector:
    app: dartscoreboard
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dartscoreboard
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: dartscoreboard.AKS_URL
    http:
      paths:
      - backend:
          serviceName: dartscoreboard
          servicePort: 80
        path: /