name: Docker Build and Push, Kubernetes deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --tag cmmanu/dartscoreboard .
        docker login -u "cmmanu" -p ${{ secrets.DOCKER_PASSWORD }} docker.io
        docker push cmmanu/dartscoreboard
