name: Docker Build and Push, Kubernetes deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker push my-image-name:$(date +%s)
        sed -i'' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
        kubectl apply -f k8s.yaml
